-- Create IDxURL Table
CREATE TABLE IDxURL (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    URL NVARCHAR(max) NOT NULL
);

-- Create IDxWord Table with an index on WORD
CREATE TABLE IDxWord (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    WORD NVARCHAR(max) NOT NULL,
);

-- Create URLxFreq Table
CREATE TABLE URLxFreq (
    IDurl UNIQUEIDENTIFIER PRIMARY KEY REFERENCES IDxURL(ID),
    IDF FLOAT NOT NULL
);

-- Create WORDxURLxFreq Table with composite primary key
CREATE TABLE WORDxURLxFreq (
    IDurl UNIQUEIDENTIFIER NOT NULL REFERENCES IDxURL(ID),
    IDword UNIQUEIDENTIFIER NOT NULL REFERENCES IDxWord(ID),
    Frequency INT NOT NULL,
    PRIMARY KEY (IDurl, IDword)
);
